"""Change user role to enum

Revision ID: 2b3c4d5e6f7g
Revises: 68aa083a9a96
Create Date: 2025-07-23 11:30:52.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3c4d5e6f7g'
down_revision = '68aa083a9a96'
branch_labels = None
depends_on = None

# The list of roles for the Enum
user_roles = sa.Enum('ADA', 'Dept Accountant', 'SCM', 'Chief Officer', name='userrole')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, altering a column with constraints requires batch mode.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=80),
               type_=user_roles,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=user_roles,
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###